"""add_webhook_notification_fields

Revision ID: 1b91bdd7e138
Revises: 664335ef7834
Create Date: 2026-06-21 03:04:28.350297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b91bdd7e138'
down_revision: Union[str, Sequence[str], None] = '664335ef7834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('has_update', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('repositories', sa.Column('webhook_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('repositories', sa.Column('watch_branch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'watch_branch')
    op.drop_column('repositories', 'webhook_enabled')
    op.drop_column('projects', 'has_update')
    op.drop_table('webhook_deliveries')
    # ### end Alembic commands ###
