"""add_github_installation_id_and_key_files

Revision ID: 664335ef7834
Revises: 241fd43a0197
Create Date: 2026-06-17 22:59:34.286777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664335ef7834'
down_revision: Union[str, Sequence[str], None] = '241fd43a0197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microservices', sa.Column('key_files', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('github_installation_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'github_installation_id')
    op.drop_column('microservices', 'key_files')
    # ### end Alembic commands ###
